# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lVurS5HwRRiuD1xmXJHSLqg06KLv372N
"""

import sys, os
import gymnasium as gym
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output

env = gym.make("Taxi-v3", render_mode=None)
observation, info = env.reset()
n_states = env.observation_space.n
n_actions = env.action_space.n
print("n_states=%i, n_actions=%i" % (n_states, n_actions))

def initialize_policy(n_states, n_actions):
    """Инициализирует политику равномерным распределением"""
    policy = np.ones([n_states, n_actions]) / n_actions
    return policy

policy = initialize_policy(n_states, n_actions)
assert type(policy) in (np.ndarray, np.matrix)
assert np.allclose(policy, 1./n_actions)
assert np.allclose(np.sum(policy, axis=1), 1)

def generate_session(env, policy, t_max=10**4, epsilon=0.1):
    """
    Играть до конца или t_max тиков.
    :param policy: массив [n_states, n_actions] с вероятностями действий
    :param epsilon: вероятность случайного действия (exploration)
    :returns: список состояний, список действий и сумма наград
    """
    states, actions = [], []
    total_reward = 0.
    s, info = env.reset()

    for t in range(t_max):
        if np.random.random() < epsilon:
            a = env.action_space.sample()
        else:
            a = np.random.choice(n_actions, p=policy[s])

        next_s, r, terminated, truncated, info = env.step(a)
        done = terminated or truncated

        states.append(s)
        actions.append(a)
        total_reward += r
        s = next_s

        if done:
            break

    return states, actions, total_reward

s, a, r = generate_session(env, policy)
assert type(s) == type(a) == list
assert len(s) == len(a)
assert isinstance(r, (float, np.floating))

sample_rewards = [generate_session(env, policy, t_max=1000)[-1] for _ in range(200)]
plt.figure(figsize=[8, 4])
plt.hist(sample_rewards, bins=20)
plt.vlines([np.percentile(sample_rewards, 50)], [0], [100], label="50'th percentile", color='green')
plt.vlines([np.percentile(sample_rewards, 90)], [0], [100], label="90'th percentile", color='red')
plt.legend()
plt.title("Распределение наград до обучения")
plt.show()

def select_elites(states_batch, actions_batch, rewards_batch, percentile):
    """Выберите состояния и действия из игры, которые имеют награды >= процентиль"""
    reward_threshold = np.percentile(rewards_batch, percentile)

    elite_states = []
    elite_actions = []

    for session_i, reward in enumerate(rewards_batch):
        if reward >= reward_threshold:
            elite_states.extend(states_batch[session_i])
            elite_actions.extend(actions_batch[session_i])

    return elite_states, elite_actions

states_batch = [[1, 2, 3], [4, 2, 0, 2], [3, 1]]
actions_batch = [[0, 2, 4], [3, 2, 0, 1], [3, 3]]
rewards_batch = [3, 4, 5]

test_result_90 = select_elites(states_batch, actions_batch, rewards_batch, percentile=90)
assert np.all(test_result_90[0] == [3, 1]) and np.all(test_result_90[1] == [3, 3])
print("✓ Тесты select_elites пройдены!")

def get_new_policy(elite_states, elite_actions, n_states, n_actions):
    """Возвращает новую политику на основе частот действий в элитных траекториях"""
    from collections import defaultdict

    new_policy = np.zeros([n_states, n_actions])
    state_action_counts = defaultdict(lambda: defaultdict(int))
    state_counts = defaultdict(int)

    for state, action in zip(elite_states, elite_actions):
        state_action_counts[state][action] += 1
        state_counts[state] += 1

    for state in range(n_states):
        if state_counts[state] > 0:
            for action in range(n_actions):
                new_policy[state, action] = state_action_counts[state][action] / state_counts[state]
        else:
            new_policy[state, :] = 1.0 / n_actions

    return new_policy

def show_progress(rewards_batch, log, percentile, reward_range=[-990, +10]):
    """Отображает прогресс обучения"""
    mean_reward = np.mean(rewards_batch)
    threshold = np.percentile(rewards_batch, percentile)
    log.append([mean_reward, threshold])

    plt.figure(figsize=[12, 4])
    plt.subplot(1, 2, 1)
    plt.plot([x[0] for x in log], label='Mean rewards')
    plt.plot([x[1] for x in log], label='Reward thresholds')
    plt.legend()
    plt.grid()
    plt.xlabel('Iteration')
    plt.ylabel('Reward')

    plt.subplot(1, 2, 2)
    plt.hist(rewards_batch, range=reward_range, bins=20)
    plt.vlines([np.percentile(rewards_batch, percentile)], [0], [100],
               label="percentile", color='red')
    plt.legend()
    plt.grid()
    plt.xlabel('Reward')
    plt.ylabel('Frequency')

    clear_output(True)
    print("mean reward=%.3f, threshold=%.3f" % (mean_reward, threshold))
    plt.show()

policy = initialize_policy(n_states, n_actions)

n_sessions = 250
percentile = 50
learning_rate = 0.5
epsilon = 0.1
log = []

print("Начало обучения CEM...")
print("=" * 50)

for i in range(100):
    sessions = [generate_session(env, policy, t_max=1000, epsilon=epsilon)
                for _ in range(n_sessions)]

    states_batch, actions_batch, rewards_batch = zip(*sessions)

    elite_states, elite_actions = select_elites(
        states_batch, actions_batch, rewards_batch, percentile
    )

    new_policy = get_new_policy(elite_states, elite_actions, n_states, n_actions)

    policy = learning_rate * new_policy + (1 - learning_rate) * policy

    epsilon = max(0.01, epsilon * 0.99)

    if i % 5 == 0:
        show_progress(rewards_batch, log, percentile)
        print(f"Итерация {i}, epsilon={epsilon:.3f}")

print("=" * 50)
print("Обучение завершено!")

print("\nФинальная оценка политики:")
final_rewards = [generate_session(env, policy, t_max=1000, epsilon=0)[-1]
                 for _ in range(100)]
print(f"Средняя награда: {np.mean(final_rewards):.2f}")
print(f"Стандартное отклонение: {np.std(final_rewards):.2f}")

env.close()